/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'birgir' at '11/2/14 2:44 AM' with Gradle 2.1
 *
 * @author birgir, @date 11/2/14 2:44 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
